### ISSUE TITLE
ecowitt protocol does not work

### ISSUE THREAD

**Issue by betogar85** [Xorfor/Domoticz-PWS-Plugin#18]
I updated to the latest version of the plug in and now the ecowitt protocol does not work

![ecowitt](https://user-images.githubusercontent.com/116471288/214449986-0b260df4-6362-4417-bcf0-207cff7e1b33.png)
![ecc](https://user-images.githubusercontent.com/116471288/214450383-10f28aaf-3380-4f15-ad2c-dbe160aa5020.png)

**Comment by betogar85** [comment]
data: {'PASSKEY': '5214AB4342302A041AD0A4FC35000A56', 'stationtype': 'EasyWeatherPro_V5.1.1', 'runtime': '1', 'dateutc': '2023-01-25+00:15:47', 'tempinf': '78.8', 'humidityin': '41', 'baromrelin': '29.811', 'baromabsin': '28.523', 'tempf': '72.3', 'humidity': '45', 'winddir': '8', 'windspeedmph': '0.00', 'windgustmph': '7.83', 'maxdailygust': '8.72', 'solarradiation': '5.92', 'uv': '0', 'tf_co2': '70.9', 'humi_co2': '59', 'pm25_co2': '1.6', 'pm25_24h_co2': '3.3', 'pm10_co2': '2.3', 'pm10_24h_co2': '3.8', 'co2': '636', 'co2_24h': '483', 'lightning_num': '0', 'lightning_time': '1673272365', 'lightning': '34', 'rrain_piezo': '0.000', 'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000', 'ws90cap_volt': '0.3', 'ws90_ver': '126', 'wh25batt': '0', 'wh57batt': '5', 'co2_batt': '6', 'wh90batt': '3.22', 'freq': '433M', 'model': 'HP2550_Pro_V1.8.0', 'interval': '20'}

**Comment by betogar85** [comment]
I forgot to mention that I added a Lightning Detection Sensor wh57
and change the array sensor for a ws90

**Comment by betogar85** [comment]
'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000'

![83381C11-553D-4FE6-90BF-E8C534F3862D](https://user-images.githubusercontent.com/116471288/214643593-29289a96-471a-47b6-8111-05df78c6f84a.jpeg)

it may be because of the new ws90 sensor

**Comment by Xorfor** [comment]
I am pretty sure, that this is because the new ws90 sensor. Probably you first used an other rain sensor and now the new one. The ws90 sensor is using `erain_piezo` instead of `dailyrainin` as expected. The plugin tries to get historical data, and there it fails. An option is to remove your device and to add it again, but you will loose your historical data! 

I tried to install the latest version of Domoticz, but what I have read, it seems to be more complicated now. I read procedures to first install Docker, etc. So I stopped the installation of Domoticz.

If you really want, that I implement the ws90 sensor (as I did on request for the wh45 sensor), but that will take some time!

Please let me know.
